In this homework, we will use the laptops price dataset from [Kaggle](https://www.kaggle.com/datasets/juanmerinobermejo/laptops-price-dataset)

### Dataset

Here's a wget-able [link](https://raw.githubusercontent.com/akki-theanalyst/Machine-Learning-Bootcamp-by-Zoomcamp/refs/heads/main/Week2/data%20(4).csv)

### Importing libraries


In [4]:
import pandas as pd
import numpy as np

### Preaparaing the dataset

**First we'll normalize the names of the columns:

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv')

The goal of this homework is to create a regression model for predicting the prices (column 'Final Price')

In [14]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [15]:
df.columns = df.columns.str.lower().str.replace(' ','_')

In [16]:
df.head()

laptop status   brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        model            cpu  ram  storage storage_type       gpu  screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  touch  final_price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [36]:
df.fillna(0)

ram  storage  screen  final_price
0       8      512    15.6      1009.00
1       8      256    15.6       299.00
2       8      256    15.6       789.00
3      16     1000    15.6      1199.00
4      16      512    15.6       669.01
...   ...      ...     ...          ...
2155   16     1000    17.3      2699.99
2156   16     1000    17.3      2899.99
2157   32     1000    17.3      3399.99
2158   16     1000    13.4      1899.99
2159   16      256    13.4      1699.99

[2160 rows x 4 columns]

Now, instead of 'Final Price', we have 'final_price'.

Next, we use only the following columns:

1. 'ram'
2. 'storage'
3. 'screen'
4. 'final_price'

### EDA

**Look at the final_price variable. Does it have a long tail?**

In [40]:
columns = ['ram', 'storage', 'screen', 'final_price']

df = df[columns]

#### Question 1
**what's the median (50% percentile) for variable 'ram' ?**

In [22]:
median = df['ram'].median()

print('median for variable ram is :', median)

median for variable ram is : 16.0


### Prepare and split the dataset

1. Shuffle the dataset (the filtered we created above), use seed 42.
2. Split the data in train/val/test sets, with 60%, 20%, 20% distribution.

In [37]:
n = len(df)
n_val = int(0.2*n)
n_test = int(0.2*n)
n_train = n - (n_val + n_test)

idx = np.arange(n)
np.random.seed(42)
np.random.shuffle(idx)

df_shuffled = df.iloc[idx]
df_train = df_shuffled.iloc[:n_train].copy()
df_val = df_shuffled.iloc[n_train:n_train+n_val].copy()
df_test = df_shuffled.iloc[n_train+n_val:].copy()

df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)



### Question 3

1. We need to deal with missing values for the column from Q1.
2. We have two options: fill it with 0 or with the mean of this variable.
3. Try both options. For each, train a linear regression model without        regularization using the code from the lessons.
4. For computing the mean, use the training only!
5. Use the validation dataset to evaluate the models and compare the RMSE of each option.
6. Round the RMSE scores to 2 decimal digits using round(score, 2)
7. Which option gives better RMSE?

In [42]:
df_train.fillna(0)

ram  storage  screen  final_price
0      32     1000    15.6      1123.29
1       4       64    14.1       201.05
2      32     1000    14.0       997.74
3      16      512    13.3      1016.00
4      32     1000    16.0      2739.00
...   ...      ...     ...          ...
1291    8      256    14.0       549.00
1292   32     1000    16.0      1999.00
1293   16      512    15.6      1059.00
1294   16      512    14.0      1671.00
1295   16      512    14.0      1056.00

[1296 rows x 4 columns]

In [45]:
df_train, df_val, df_test

(      ram  storage  screen  final_price
 0      32     1000    15.6      1123.29
 1       4       64    14.1       201.05
 2      32     1000    14.0       997.74
 3      16      512    13.3      1016.00
 4      32     1000    16.0      2739.00
 ...   ...      ...     ...          ...
 1291    8      256    14.0       549.00
 1292   32     1000    16.0      1999.00
 1293   16      512    15.6      1059.00
 1294   16      512    14.0      1671.00
 1295   16      512    14.0      1056.00
 
 [1296 rows x 4 columns],
      ram  storage  screen  final_price
 0     32     1000    16.0      2599.00
 1     16      512    15.6       999.00
 2     12      512    15.6       477.28
 3      8      256    13.6      1519.00
 4      8      512    15.6       402.99
 ..   ...      ...     ...          ...
 427    8      128    13.0      1049.00
 428    8      256    13.3       799.00
 429    8      512    14.0       565.54
 430   16      512    14.0       738.00
 431    4       64    14.0       452.00


In [50]:
y_train = df_train.final_price.values
y_val = df_val.final_price.values
y_test = df_val.final_price.values
y_train

array([1123.29,  201.05,  997.74, ..., 1059.  , 1671.  , 1056.  ],
      shape=(1296,))

In [51]:
del df_train['final_price']
del df_val['final_price']
del df_test['final_price']

# Model training

In [52]:
def train_linear_regression(X, y):

    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])
    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)

    return w[0], w[1:]

def prepare_X(df, fillna_values):

    df = df.fillna(fillna_values)
    X = df.values
    return X

def rmse(y, y_pred):

    error = y_pred - y
    mse = (error**2).mean()
    return np.sqrt(mse)

In [55]:
X_train = prepare_X(df_train, fillna_values = 0)

In [56]:
w_0, w = train_linear_regression(X_train, y_train)

In [59]:
w_0, w

(np.float64(676.8954853003995),
 array([ 43.70681555,   0.86506867, -36.10399833]))

In [60]:
y_pred = w_0 + X_train.dot(w)

In [61]:
y_pred

array([2377.35987681,  398.02076576, 2435.12627415, ..., 1255.89731808,
       1313.66371541, 1313.66371541], shape=(1296,))

In [ ]:
rmse(y_train, y_pred)