# Week 1 Lecture Notes.

### 1.1 Introduction to Machine Learning

1. Example: recommending a price for a car, given its properties such as: age, mileage, model, no. of doors, etc.
2. Pattern can be found in the data which can be modelled.
3. Essence of ML: given data, have a model learn pattern in the data.
4. Data consists of:
    a. Features: what we knoe about car (i.e its properties)
    b. Target: What we want to predict (i.e. its price)

5. User can provide information on a car they want to sell. This data is extracted.
6. Price(target) is predicted and suggested to the user as an appropriate price.   

### 1.2 ML vs Rule-Based Systems

This lesson cover a details comparison between rule-based and ML systems. For example -: 
a. An email spam detection system

We want to develop a spam detection system using a classifier.

1. Rule-based approach

Take all the spam email messages and try to identify what makes a message spam. We could come up with explicit rules based on the sender, subject, etc.
However spam messages evolve and require frequent update, leading inevitably large number of rule and logic which will be nightmare to maintain.

2. Machine Learning Approach

We get the data, defines and calculate features, train and use the model. 

a. Getting the data: we could have a spam button which users can press to indicate an e-mail is spam

b. Defining features: we could start off with some rules, e.g. length of subject greater than 10, length of body greater than 10, sender has a certain domain, sender e-mail address has a certain pattern, and so on. These are just some examples of features, there can be more/different ones. Then for a given e-mail, we can put its data in a vector:[1,1,0,1,0,1], This would indicate then the length of the subject is greater than 10, length of body is greater than 10, etc. Say that the user designated this e-mail as spam, then the target variable is also 1. We do this for many e-mails and get a matrix with the features and a vector with target variables.

c. Train model: features and target variables go into ML model. We fit/train the model and determine some unknown coefficients that minimize the error between predictions and the target.

d. Use model: now that the model has been trained, we can put new data into it and predict the target.


# 1.3 Supervised Machine Learning.

In supervised Machine learning we trained a model for given output data.
We provided the data and the target variable and the ML model learn the pattern in the data. These pattern can be used to generlize to new samples. In spam email example we did the same.

The feature matrix is a two dimensional array in which each rows are our observation or sample and columns are features.It is designated with **X**. The target is a vector designated with **y**.**X** is our input and **y** is our output.

             g(X) = y

# 1.4 CRISP-DM

CRISP-DM is a methodology for organizing ML projects. It stands for Cross-Industry Standard Processing Data Mining. There are 6 steps.

          [Data Understanding] --> [Data preparation] --> [Modeling]

           [Businness Understanding]<-- [Deployment]<-- [Evaluation] <--
                                            

ML Project: understand the problem, collect the data, train the model, use it.

We will use the spam detection example.

E-mail → Model → spam / not spam

### Step 1: Bussiness Understanding

Goal is to identify the problem to solve. Understand if problem is important and how to measure success. Here we decide whether we need ML.

Spam detection: users complain about spam. What is the extent of the problem? One users or many? Do we need ML? Define the goal: e.g. reduce amount of spam messages, reduce amount of complaints about spam. Goal should be measurable: reduce amount of spam messages by 50%.

### Step 2: Data Understanding.

Make sure data is available, or what is missing, and how to collect/acquire it.

Spam detection: spam button. Is the data behind this button good enough? Is it reliable? Do we track it correctly? Is the dataset large enough? Do we need to get more data?

### Step 3: Data preparation

The data needs to be transformed such that it can be used in the ML model. We may need to clean the data, extract features, build pipelines, convert into tabular form.

### Step 4: Modeling

We now have the data in the right format. We try different models and we pick the best one. For example logistic regression, decision tree, neural network, etc. We may need to go back to data preparation to fix issues with the data or do more feature engineering if required.This is root of Machine learning so most of the time we spending on modeling.


### step 5: Evaluation

Now we will assess how well the model is performing with respect to the goal we defines under Business Understanding. Have we reached the goal? Do our metrics improve? Did we solve/measure the right thing? Was the goal achievable? Do we need to update the goal?

### step 6: Deployment

This step goes hand in hand with Evaluation. We deploy the model and monitor it when online. Usually we first deploy to a subset of users.

This process is typically iterated over based on learnings.

It is a good idea to start simple and go quickly through all the steps. Then you iterate to introduce further improvements.



# 1.5 Modeling step (Model selection process)

The modeling step is where we try different models and choose the best model. This is where the actual ML happens.

Let's say we train in July using data **X** with output **y**and we set up model **g**
. Then we evaluate in August and find out our model has an accuracy of 0.7. Ideally we would be able to travel to the future and get the data from then and set our model up with that data. That obviously cannot happen. Therefore we do something else. We split the data. For example we take a subset of 20% (representing August) and we 'hide' that data. We train only with the remaining 80% (July). We call the 80% the training data and the 20% the validation data.

So using the training data we get a model **g** from training with **X** and **y**.

The validation data also has data **Xv** and **yv**. We can use our model to make predictions: **g(Xv)** = *y'v*

The difference between **y'** and **y** is our accuracy. We can do this for various models such as logistic regression, decision tree, neural network, etc. and compare accuracies.

The problem with this approach is that one of the models might have gotten lucky. In statistics this is called Multiple Comparison Problem. ML models are probabilistic, so we need to guard against this.

To address this, we introduce a testing dataset. For example: 60% training, 20% validation, 20% test. The test data is hidden. We do the model selection: use **X**and **y**  to get model ***g***. We validate it by using model *g*and 
 to make predictions 
. We select the best model. Then at the very end, we test the model to ensure it didn't get particularly lucky. It is basically an extra round of validation with 
 to make predictions 
. The accuracy of the test data should be in line with the validation data.


# Introduction to Numpy

### first import numpy 



In [1]:
import numpy as np

check version

In [2]:
np.__version__

'2.2.4'

### Create arrays

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.full(10,0) # for specific size and specific number

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
## Convert python list into array

a = [3,4,5,7,9]

arr = np.array(a)

In [14]:
arr

array([3, 4, 5, 7, 9])

In [15]:
## Accessing the element in array

arr[3]

np.int64(7)

In [18]:
# modify array
arr[3] = 10
arr

array([ 3,  4,  5, 10,  9])

In [19]:
# array based on range(0 tp 10)


np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [21]:
# creating array from 0 to 1 with 11 element

np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
np.linspace(10, 100, 11)

array([ 10.,  19.,  28.,  37.,  46.,  55.,  64.,  73.,  82.,  91., 100.])

### Multi-dimensional array

In [24]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
# We can create multidimensional array using list of list

a = [[1,2,3,2], [4,2,1,3]]

arr = np.array(a)

In [26]:
arr

array([[1, 2, 3, 2],
       [4, 2, 1, 3]])

In [28]:
# we want to shape of array 

arr.shape # gives dimension of arr means rows and column

(2, 4)

In [32]:
# Accesing element in multidimensional array

arr[0,1] = 20

In [33]:
arr

array([[ 1, 20,  3,  2],
       [ 4,  2,  1,  3]])

In [34]:
arr[:, 3]

array([2, 3])

In [35]:
# changing the arr

arr[:, 3] = [5,6]

In [36]:
arr

array([[ 1, 20,  3,  5],
       [ 4,  2,  1,  6]])

In [39]:
#Randomly generated array with 5 rows and 2 columns:

np.random.seed(9) # seed to make result reproducible
array = np.random.rand(5, 3)

In [40]:
# we perform all the mathematical operation on array

100 * array 

array([[ 1.03741539, 50.18745921, 49.57732931],
       [13.3829529 , 14.21110855, 21.85586756],
       [41.85081805, 24.81011684,  8.40596512],
       [34.54986401, 16.67763465, 87.85590855],
       [95.09640316,  3.87483758, 69.91073914]])

In [45]:
# Now from standard normal distribution
np.random.randn(5, 3)

array([[-0.5961597 , -0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525, -0.87810789],
       [-0.15643417,  0.25657045, -0.98877905],
       [-0.33882197, -0.23618403, -0.63765501],
       [-1.18761229, -1.42121723, -0.1534952 ]])

In [48]:
np.random.randint((5, 3))

array([2, 0])

### Element wise operation


In [49]:
a = np.arange(5)

In [50]:
a

array([0, 1, 2, 3, 4])

In [51]:
10 + a

array([10, 11, 12, 13, 14])

In [52]:
a * 2

array([0, 2, 4, 6, 8])

In [53]:
a/2

array([0. , 0.5, 1. , 1.5, 2. ])

In [54]:
((a + 10)/2) * 4

array([20., 22., 24., 26., 28.])

In [55]:
a > 10*a

array([False, False, False, False, False])

a == a

In [57]:
a < 2

array([ True,  True, False, False, False])

In [59]:
a[a<4]

array([0, 1, 2, 3])

# Linear Algebra Refresher

### Vector operation

we have vector u and v below 

   \begin{bmatrix}
           2 \\
           4 \\
           5 \\
           6 \\
         \end{bmatrix}



                


         


Let's apply numpy in linear algebra

In [60]:
u = np.array([2,4,5,6])

v = np.array([1, 0, 0, 2])

In [62]:
u, v

(array([2, 4, 5, 6]), array([1, 0, 0, 2]))

In [63]:
# multiplication of vector with scaler

2 * u

array([ 4,  8, 10, 12])

In [64]:
# Adding two vector

u + v

array([3, 4, 5, 8])

In [65]:
# Dot product (Inner product)

np.dot(u, v)

np.int64(14)

In [66]:
u.dot(v)

np.int64(14)

In [67]:
u @ v

np.int64(14)

In [ ]:
# here is code implementation dot product

def vector_vector_multiplication(u, v)